import assert from "node:assert/strict";
import { test } from "node:test";
import { applicationTools } from "../../src/app/tools.js";
import { taskInput } from "../../src/app/validation.js";
import type { Task } from "../../src/core/types.js";
import { actor, discussion, setup } from "../tasks/helpers.js";

const legacyInput = {
  ...discussion,
  orchestration: { mode: "model", maxDecisions: "1", maxMinutes: "240" },
  discussion: { mode: "round_robin", maxRounds: "4", maxMinutes: "30" },
};

test("legacy normalized tool input keeps the original task identity and explicit pause on replay", async () => {
  const h = setup();
  try {
    h.config.ai.enabled = true;
    const task = await h.service.create(actor, taskInput(legacyInput));
    // Identity generated by the pre-removal parser and createTask at 6b5411e.
    assert.equal(task.id, "task_e80ca0d35ad9193d057d30d8cd32fed2");
    task.orchestration = { mode: "model", maxDecisions: 1, maxMinutes: 240 };
    task.discussion.maxRounds = 4;
    task.discussion.maxMinutes = 30;
    task.discussion.paused = true;
    task.status = "paused";
    h.service.records.save(task);
    const replay = await h.service.create(actor, taskInput(legacyInput));
    assert.equal(replay.id, task.id);
    assert.equal(replay.status, "paused");
    assert.equal(replay.discussion.paused, true);
    assert.equal(h.store.list<Task>("tasks").length, 1);
    assert.equal(h.service.records.participants(replay).length, 2);
  } finally {
    h.close();
  }
});

test("new tasks neither validate nor persist obsolete execution quotas", async () => {
  const h = setup();
  try {
    h.config.ai.enabled = true;
    const task = await h.service.create(
      actor,
      taskInput({
        ...legacyInput,
        orchestration: { mode: "model", maxDecisions: 0, maxMinutes: -1 },
        discussion: { mode: "round_robin", maxRounds: 0, maxMinutes: -1 },
      }),
    );
    assert.deepEqual(task.orchestration, { mode: "model" });
    assert.equal("maxRounds" in task.discussion, false);
    assert.equal("maxMinutes" in task.discussion, false);
  } finally {
    h.close();
  }
});

test("task creation tool no longer advertises local execution quotas", () => {
  const services = {} as Parameters<typeof applicationTools>[0];
  const tool = applicationTools(services, actor).find((entry) => entry.name === "task_create");
  assert.ok(tool);
  const schema = tool.parameters as {
    properties: Record<string, { properties: Record<string, unknown> }>;
  };
  assert.deepEqual(Object.keys(schema.properties.orchestration?.properties ?? {}), ["mode"]);
  assert.deepEqual(Object.keys(schema.properties.discussion?.properties ?? {}), ["mode"]);
});
